# Site Settings
title: Sufiyan Malek
tagline: Developer Blog Posts
email: your-email@domain.com
description: >
  The demo site for Bulma Clean Theme, made for Jekyll and GitHub pages websites
#baseurl: "/site"
url: "https://www.sufimalek.github.io"
#permalink: pretty
permalink: /:title/
favicon: /img/logo_200x200.png
gh_sponsor: sufimalek
#hide_share_buttons: true
read_time: true # reading time estimates, e.g. true
words_per_minute: 130 # 200
mathjax: # MathJax equations, e.g. true
date_format: "%B %-d, %Y"
paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
#  shortname: smalek


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Sufiyan A. Malek"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge
include: ['_pages']
footer_menu: example_footer_menu

collections:
  stories:
    output: true
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false